#!/bin/bash
# edit command
set -e

ECMTMP=~/.ecm_tmp_`date +%Y-%m-%d_%H-%M-%S.txt`
trap 'rm $ECMTMP' ERR

echo "$@" | tr ' ' '\n' > $ECMTMP
vim $ECMTMP < /dev/tty > /dev/tty
eval `cat $ECMTMP` | tr '\n' ' '
rm $ECMTMP
